### ISSUE TITLE
Questions: Sinkable, sink

### ISSUE THREAD

**Issue by masters3d** [val-lang/specification#5]
I saw your talk posted only CPPNow. I was following most of the content except for `sink`. Is this like source -> sink? What is the definition of something that is sinkable? (Beyond escaping, perhaps is it like Sendable in Swift? )  
(Sinkable sounds to me like Syncable )
Can you give some examples from a swift (or rust ) perspective for sink? 

Thanks!

**Comment by kyouko-taiga** [comment]
It is a little difficult to give examples of `sink` in Swift, because Swift doesn't have move semantics, so let's do it in Rust (disclaimer: I'm not a Rust expert).

TL;DR; `sink` is pass-by-move (the default in Rust) whereas `let` is pass by immutable borrow. In a way, that means Val and Rust have different defaults.

For the longer explanation, let's compare how both languages operate on a simple example. When you pass something by value in Val, the underlying semantics is similar to an immutable borrow in Rust, because in the absence of reference semantics there is no observable difference for the callee.

For example, this function
```val
// val version
fun longer_of(_ x: String, _ y: String) -> String {
  if x.count() < y.count() { y.copy() } else { x.copy() }
}
```
can be translated in Rust like that
```rust
// rust version
fn longer_of(x: &String, y: &String) -> String {
  if x.len() < y.len() { y.clone() } else { x.clone() }
}
```

A `sink` parameter indicates that the callee intends to take ownership of the argument, presumably to make it escape (e.g., to return it). So, this function
```val
// val version
fun longer_of(_ x: sink String, _ y: sink String) -> String {
  if x.count() < y.count() { y } else { x }
}
```
can be translated in Rust like that
```rust
// rust version
fn longer_of(x: String, y: String) -> String {
  if x.len() < y.len() { y } else { x }
}
```
Notice in this second example that we no longer need to copy/clone the returned string, because now we have its ownership.

**Comment by masters3d** [comment]
Okay so `sink` in val is like a var `moveonly` in a future swift refenced here:
https://github.com/apple/swift/blob/main/docs/OwnershipManifesto.md

Thanks!
